@baseUrl = http://localhost:3333
@authToken = {{Authenticate.response.body.access_token}}

# @name Create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name":"Richard Lirio",
    "email": "richard@hotmail.com",
    "password": "123456"
}

###

# @name Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "richardlirio@hotmail.com",
    "password": "123456"
}

###

# @name Create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

